### ISSUE TITLE
Discussion about tension in flex cable

### ISSUE THREAD

**Issue by banchan86** [arnefmeyer/mousecam#1]
Hi, just wanted to open a discussion about tension and how to resolve that. I haven't tested it out yet, but after building the device, seems like with a freely moving animal there will be a tension build up in the flex cable after it twists around for a while that might either impede movement or lead to damage in the cable. Just wondering what are your thoughts on it (will it not be too much of a problem, are there ways to resolve it, and how long can the mice be observed without relieving the tension by resetting the mice)

**Comment by arnefmeyer** [comment]
There is no risk of damaging the cable (at least for mice). Tension build up might occur when the cable twists around a couple of times but animals quickly "learn" to untwist the cable. Tension can be further reduced by extending the camera cable (e.g., https://shop.pimoroni.com/products/camera-cable-joiner-extender-for-raspberry-pi).

We have done recordings for more than an hour without manually untwisting the cable and did not observe any substantial differences in behavior compared to mice without camera. Of course, this depends on the behavior you want to study. If the behavior involves a lot of rotations in one direction you might consider attaching the whole raspberry pi to a slip ring commutator so it can rotate with the animal. Power and trigger signals (3 wires) could simply be transmitted using the commutator.

note that we are working on a newer version of the camera with much thinner cable but this will take some more time.

**Comment by banchan86** [comment]
Hey arne thanks! mounting the raspberry pi on a slip ring commutator sounds promising
