### ISSUE TITLE
IR filter in new Pi cameras

### ISSUE THREAD

**Issue by apaks** [arnefmeyer/mousecam#2]
Hello,

First, thanks for such a detailed instructions on building the implant.

I was wondering whether you tried to remove IR filter from the new Pi cameras. I was not able to locate it (see pictures below). However, I tried to remove the lens and it makes images brighter under IR illumination but not enough to record good quality videos. 

Also, did you try to use red LED to illuminate mouse eyes? 

Thanks,

![20210630_201717](https://user-images.githubusercontent.com/18731254/124184013-fd97f800-da86-11eb-97af-9a0f83a2aa03.jpg)
![20210630_202359](https://user-images.githubusercontent.com/18731254/124184016-fd97f800-da86-11eb-86c9-9225768430ae.jpg)

**Comment by arnefmeyer** [comment]
In some newer camera modules, the IR filter is glued on top of the CMOS sensor. Not sure if it is possible to remove the filter without damaging the sensor. However, arducam is selling a similar camera module without IR filter:
https://www.arducam.com/product/1-4-5-noir-mpspy-camera-module-sensor-flex-cable-raspberry-pi/

**Comment by apaks** [comment]
Thanks for the reply, I will try arducam cameras.
